name = "StringTemplates"
uuid = "59c22e0c-4e04-425f-9782-11a552c58a8d"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]
version = "0.1.0"

[deps]
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[weakdeps]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Aqua = "0.8"
julia = "1"

[targets]
test = ["Test", "Aqua"]
